# -*- coding: utf-8 -*-
"""train_model_cleaned.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s73V_43umza0UUsF7uMYh8VD8mONixCz#scrollTo=j_fiTPDUGrzS
"""


# Required Libraries
import os
import joblib
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler

# Create Output Folder
os.makedirs("saved_models", exist_ok=True)

#  Simulate MFCC Feature Data (Replace with real extracted MFCC features in production)
num_samples = 100
mfcc_dim = 40 * 174  # flattened MFCC size
X_features = np.random.rand(num_samples, mfcc_dim)

#  Dummy Labels
labels_gender = np.random.randint(0, 2, size=num_samples)      # 0 = Male, 1 = Female
labels_age = np.random.randint(0, 3, size=num_samples)         # 0 = Youth, 1 = Adult, 2 = Senior
labels_emotion = np.random.randint(0, 8, size=num_samples)     # 8 emotion classes

#  Train Gender Model
gender_scaler = StandardScaler()
X_scaled_gender = gender_scaler.fit_transform(X_features)
gender_model = RandomForestClassifier()
gender_model.fit(X_scaled_gender, labels_gender)

# Save gender model & scaler
joblib.dump(gender_model, "saved_models/model_gender_voice.joblib")
joblib.dump(gender_scaler, "saved_models/scaler_gender_voice.joblib")

#  Train Age Model
age_scaler = StandardScaler()
X_scaled_age = age_scaler.fit_transform(X_features)
age_model = RandomForestClassifier()
age_model.fit(X_scaled_age, labels_age)

# Save age model & scaler
joblib.dump(age_model, "saved_models/model_age_voice.joblib")
joblib.dump(age_scaler, "saved_models/scaler_age_voice.joblib")

#  Train Emotion Model
emotion_scaler = StandardScaler()
X_scaled_emotion = emotion_scaler.fit_transform(X_features)
emotion_model = RandomForestClassifier()
emotion_model.fit(X_scaled_emotion, labels_emotion)

# Save emotion model & scaler
joblib.dump(emotion_model, "saved_models/model_emotion_voice.joblib")
joblib.dump(emotion_scaler, "saved_models/scaler_emotion_voice.joblib")

print("All models and scalers saved successfully to 'saved_models/'")







